apiVersion: 1

# SATH v1.7+ - InfluxDB Datasource Configuration
# Bucket se configura dinamicamente via variable de entorno

deleteDatasources:
  - name: InfluxDB
    orgId: 1

datasources:
  - name: InfluxDB
    uid: influxdb-sath
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: trading_bot
      defaultBucket: ${INFLUXDB_BUCKET:trading_decisions}
      tlsSkipVerify: true
    secureJsonData:
      token: ${INFLUXDB_TOKEN:e961eeb978537b3f67684065435613c5d13a29ba7a38f7768d929126eb11423b}
    isDefault: true
    editable: true
