apiVersion: 1

# SATH v2.2 - InfluxDB Datasource Configuration

deleteDatasources:
  - name: InfluxDB
    orgId: 1

datasources:
  - name: InfluxDB
    uid: influxdb-sath
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: trading_bot
      defaultBucket: trading_decisions
      tlsSkipVerify: true
    secureJsonData:
      token: e961eeb978537b3f67684065435613c5d13a29ba7a38f7768d929126eb11423b
    isDefault: true
    editable: true
